---
- name: Install docker
  ansible.builtin.include_tasks: "{{ tasks_dir }}/docker/install.yaml"

- name: Set variables
  ansible.builtin.set_fact:
    remote_path: ~/docker-compose.yml
    local_path: "{{ vault_files_path }}/docker-compose.yml"
    project_path: .

- name: Include update docker-compose
  ansible.builtin.include_tasks: "{{ tasks_dir }}/docker/update-compose.yaml"
  vars:
    update_compose_remote_path: "{{ remote_path }}"
    update_compose_local_path: "{{ local_path }}"
    update_compose_project_path: "{{ project_path }}"

- name: Copy init-vault.sh
  ansible.builtin.copy:
    src: "{{ vault_files_path }}/init-vault.sh"
    dest: ~/init-vault.sh
    mode: '0755'

- name: Read remote vault-config.json
  ansible.builtin.stat:
    path: ~/config/vault-config.json
  register: remote_config

- name: Read local vault-config.json
  ansible.builtin.stat:
    path: "{{ vault_files_path }}/vault-config.json"
  register: local_config
  delegate_to: localhost

- name: Check file content and set variables
  ansible.builtin.set_fact:
    config_different: "{{ not remote_config.stat.exists or remote_config.stat.checksum != local_config.stat.checksum }}"

- name: Are they different?
  ansible.builtin.debug:
    msg: "{{ config_different }}"

- name: Actions to do if files are different
  when: config_different
  block:
    - name: Ensures ~/config/ dir exists
      ansible.builtin.file:
        path: ~/config/
        state: directory
        mode: '0755'

    - name: Copy vault-config.json
      ansible.builtin.copy:
        src: "{{ vault_files_path }}/vault-config.json"
        dest: ~/config/vault-config.json
        mode: '0644'
      register: config_copy_result

    - name: Exec docker-compose down
      community.docker.docker_compose_v2:
        project_src: .
        state: absent
      when: remote_file.stat.exists

    - name: Exec docker-compose up
      community.docker.docker_compose_v2:
        project_src: .
        state: present
